### ISSUE TITLE
Npm install creates root:root folder 

### ISSUE THREAD

**Issue by lukasoppermann** [mhart/alpine-node#98] opened 2017-07-21 10:49 UTC
Hey,

somehow I still have the problem noted in #94.

When I run `docker run mhart/alpine-node node --version` I get `8.2.1` and the same for when I run  `docker exec node node --version`. So I am pretty sure I am on the latest release.

In my `docker-compose.yml` I mount the app folder:

```yaml
volumes:
            - ../:/usr/app/
```

My Dockerfile:

```yaml
FROM mhart/alpine-node:latest
RUN apk update
RUN apk add git
ENV NODE_ENV production

RUN npm i -g forever

WORKDIR /usr/app


EXPOSE 8080

CMD sh docker/start.sh
```

The `/usr/app` folder is owned by `1001:ping` when I run `ls -la` on the container.

The `docker/start.sh` has the following in it:

```bash
#!/bin/bash
if [ -z "$NODE_ENV" ]; then
    export NODE_ENV=production
fi

npm install --only=production

forever app.js -m 5000
```

Am I missing something? Please let me know if you need more info or if I need to try something. Thank you very much.

**Comment by mhart** [comment] 2017-07-21 12:42
When you say you have the same problem, you mean the ownership of `/usr/lib/node_modules/npm` is `501:dialout`?

**Comment by lukasoppermann** [comment] 2017-07-21 12:48
Sorry, no. The problem is that the `node_modules` directory, so `/usr/app/node_modules` on the container is `root:root` all other files on the container (the ones that are put there via the volume) are `ping:1001`.

I am deploying with capistrano, using a deploy user (not root) which fails because it can not delete old releases, due to missing permissions (it can delete all files with `ping:1001`).

I hope this is less confusing.

**Comment by mhart** [comment] 2017-07-21 13:19
I'm assuming the `ping:1001` permissions are on files that are on the machine you're running docker from (ie, coming from outside the image)?

The user for this image is root, so all permissions being root is expected. If you're changing the user, then it's not going to have permissions to delete files owned by root.

As an aside, it sounds like your deploy strategy might be a bit unusual? Normally you create a new container and just remove the old one (this is usually very fast with layer caching). Modifying the contents of containers outside of a Dockerfile means that you're no longer in a reproducible state.

**Comment by lukasoppermann** [comment] 2017-07-21 14:39
Hey @mhart this is correct. So from your comment I understand, that this is expected behaviour? Is there any way around this? The files are not just on docker, but it is a shared volume that is also a directory on the ubuntu file system. 

I know it is not typical, but I am not building a service, basically just a simple website. I am not changing anything on the docker side without destroying the container, just the files that are executed (html, js, css). 

I have a git repo which serves as my source of truth. I know it is not conventional, but I am currently pretty satisfied with the quick way of updating it, I might reconsider at a later point of course.

**Comment by mhart** [comment] 2017-07-21 14:53
Of course – you could change the user in your Dockerfile to whatever you need it to be before you run your command. Use the `USER` command for this (probably want it after your `RUN npm i -g forever` line, as you'll want that to run as root because it's installing globally)

https://docs.docker.com/engine/reference/builder/#user

Closing this as it's not an issue with the image

**Closed as completed by mhart** 2017-07-21 14:53 UTC

**Comment by lukasoppermann** [comment] 2017-07-21 15:03
Will look into it, thank you very much for your help.
