### ISSUE TITLE
Can't install npm package globally with 8.x version.

### ISSUE THREAD

**Issue by cnnblike** [mhart/alpine-node#95] opened 2017-06-24 04:47 UTC
Hi, I used your images as base to build and test things in my CI. Everything is fine until the recent version:8.x.
In short, the problem might be in the npm permissions, but shouldn't we be root in the image? Excuse me if I asked something stupid.

```
FROM mhart/alpine-node:6
RUN  npm install hexo-cli -g
```
worked. 
but 
```
FROM mhart/alpine-node:latest
RUN npm install hexo-cli -g
```
failed.

the build log is like 
```
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> hexo-util@0.6.0 build:highlight /usr/lib/node_modules/hexo-cli/node_modules/hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

sh: can't create highlight_alias.json: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-util@0.6.0 build:highlight: `node scripts/build_highlight_alias.js > highlight_alias.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-util@0.6.0 build:highlight script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! hexo-util@0.6.0 postinstall: `npm run build:highlight`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the hexo-util@0.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-24T04_40_04_950Z-debug.log
The command '/bin/sh -c npm install hexo-cli -g' returned a non-zero code: 243
```

**Comment by mhart** [comment] 2017-07-07 21:49
I suspect this is a dupe of https://github.com/mhart/alpine-node/issues/94 which has now been resolved

**Closed as completed by mhart** 2017-07-07 21:49 UTC
